### ISSUE TITLE
self-hosted-ubuntu-22.04 doesn't bring gcc

### ISSUE THREAD

**Issue by jremmet** [phytec/phybuilder-container#1]
Switching from ubuntu-latest to self-hosted-ubuntu-22.04 fails with
`error: command 'gcc' failed: No such file or directory`

 https://github.com/phytec/ptf-dev/actions/runs/4301034956

We need to install a python-package which gets build.

Compare installed packages to https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#installed-apt-packages

**Comment by smk-embedded** [comment]
1. to your error: -y is missing from the command line
2. the mentioned fix is already included in the image
3. I added LANG which was not set, please test again

**Comment by jremmet** [comment]
gihub runner allows to not have "-y" and the man page of DEBIAN_FRONTEND also suggest this:
https://www.cyberciti.biz/faq/explain-debian_frontend-apt-get-variable-for-ubuntu-debian/
`
noninteractive – You use this mode when you need zero interaction while installing or upgrading the system via apt. It accepts the default answer for all questions. It might mail an error message to the root user, but that’s it all. Otherwise, it is totally silent and humble, a perfect frontend for automatic installs. One can use such mode in Dockerfile, shell scripts, cloud-init script, and more.
`

The runners show this differences:
github:
```
echo "sudo DEBIAN_FRONTEND $DEBIAN_FRONTEND"
sudo DEBIAN_FRONTEND noninteractive
```

phytec:
```
echo "sudo DEBIAN_FRONTEND $DEBIAN_FRONTEND"
sudo: unable to send audit message: Operation not permitted
sudo DEBIAN_FRONTEND noninteractive
```
Also I can find this via grep in github runner only:
`/etc/environment:DEBIAN_FRONTEND=noninteractive`

**Comment by jremmet** [comment]
github:
```
sudo grep DEBIAN_FRONTEND /etc
/etc/skel/.nvm/Dockerfile:ENV DEBIAN_FRONTEND noninteractive
/etc/environment:DEBIAN_FRONTEND=noninteractive
```

phytec;
```
sudo grep DEBIAN_FRONTEND /etc
sudo: unable to send audit message: Operation not permitted
/etc/sudoers:Defaults env_keep += "DEBIAN_FRONTEND"
```

**Comment by smk-embedded** [comment]
correct, so apt-get should work as expected, tried yesterday and it worked, so maybe another issue?
audit error is yet another issue

**Comment by jremmet** [comment]
Didn't get it "It accepts the default answer for all questions." suggest that "[Y/n]" is answered automatically.
I'll compare the apt settings.

**Comment by smk-embedded** [comment]
I will archive that. At some point we might try it again to move to self-hosted runners.
