### ISSUE TITLE
Question: BSP build tools 

### ISSUE THREAD

**Issue by msft-takend** [phytec/phybuilder-container#11]
Is the intent here to be able to build the BSP using this image?  Seems like a lot of the tools are missing.

**Comment by smk-embedded** [comment]
Hi there, sorry for the late response. I did not get a notification. We are still mail focused and github is second class citizen. Working on that.
Yes the intend is to use it as a replacement for CROPS. As there are too many use-cases, we deviate from CROPS and cannot reuse it properly. This repo was actually not correctly maintained as we are reworking some internal CI workflows. Hopefully in the next weeks we will improve it and correctly mirror our current build containers public. Sorry for the current inconvenience. I was going a little bit ahead with making this public already. Feel free to get it touch about any issues.
Regards, Stefan
