### ISSUE TITLE
rsync is missing in 20.04 image

### ISSUE THREAD

**Issue by shyd** [phytec/phybuilder-container#8]
Hi, this week I started with phyLinux and followed the hardknott guide. `bitbake` fails at recipe `linux-imx` because `rsync` is missing.
It works if I create a local image with rsync. Please consider adding rsync to your image(s).

Best Regards
Dennis

**Comment by smk-embedded** [comment]
Hi Dennis, sorry missed the notification on that issue. I agree and issue is fixed in #10
